[package]
name = "corsair-keyb-led"
version = "0.1.0"
authors = ["Patrick Strang <patrick@strang.io>"]
edition = "2018"


[dependencies]
cuesdk-sys = { path = "cuesdk-sys", version = "0.1.0" }

[target.'cfg(windows)'.dependencies]
widestring = "0.4.2"
winapi = "0.3.9"
