[package]
name = "corsair-keyb-led"
version = "0.1.0"
authors = ["Patrick Strang <patrick@strang.io>"]
edition = "2018"
exclude = [
    "**/.gitignore",
    ".travis.yml"
]

[dependencies]
cuesdk-sys = { path = "cuesdk-sys", version = "^1.0.0" }
