[package]
name = "corsair-keyb-cli"
version = "0.1.0"
authors = ["Patrick Strang <patrick@strang.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
